export const widgetConfig = {
  widgets: [
    {
      id: "units-covered",
      title: "Units Covered",
      type: "column",
      width: 2,
      height: 2,
      x: 0,
      y: 0,
      downloadable: true,
      fullscreen: true,
    },
    {
      id: "customer-experience",
      title: "Customer Experience",
      type: "line",
      width: 2,
      height: 2,
      x: 2,
      y: 0,
      downloadable: true,
      fullscreen: true,
    },
    {
      id: "usage-speed",
      title: "Usage Based on Download Speed",
      type: "pie",
      width: 2,
      height: 2,
      x: 4,
      y: 0,
      downloadable: true,
      fullscreen: true,
    },
    {
      id: "site-stats",
      title: "Site Stats",
      type: "stats",
      width: 2,
      height: 2,
      x: 6,
      y: 0,
      downloadable: false,
      fullscreen: false,
    },
    {
      id: "satisfaction-trend",
      title: "Satisfaction Trend",
      type: "line",
      width: 4,
      height: 2,
      x: 8,
      y: 0,
      downloadable: true,
      fullscreen: true,
    },
    {
      id: "map",
      title: "Geography",
      type: "map",
      width: 8,
      height: 4,
      x: 0,
      y: 2,
      downloadable: false,
      fullscreen: true,
    },
    {
      id: "network-genie",
      title: "Network Genie",
      type: "chat",
      width: 4,
      height: 4,
      x: 8,
      y: 2,
      downloadable: false,
      fullscreen: false,
    },
    {
      id: "data-grid",
      title: "Network Insights Data",
      type: "grid",
      width: 12,
      height: 4,
      x: 0,
      y: 6,
      visible: false,
      downloadable: true,
      fullscreen: true,
    },
  ],
};
